Útvíkkaður kóði og regex frá fyrra verkefni
Upplysingaverkfraedi/sqlite-tyrell pull request #2
Opened 2024-09-30 16:55 UTC by IngvarAtli

útvíkkaði kóðann og reglulegu segðina frá fyrri verkefni, setti einning leiðbeiningar um það hvernig ætti að keyra kóðann í README skjal. Endilega skoðið kóðann og sjáið hvort hann virki ekki fyrir ykkur, þá sérstaklega Logi til að athuga hvort kóðinn er ekki í samræmi við þinn hluta í lið 3. .

2024-10-02 16:35 UTC, Jon-slow97 requested changes
Tillaga að breytingum til að vinna með SQL gagnagrunninn

2024-10-02 16:35 UTC, Jon-slow97 commented on timataka.py
> +
```suggestion
import sqlite3
```

2024-10-02 16:35 UTC, Jon-slow97 commented on timataka.py
> +
```suggestion
def insert_into_database(csv_file, db_file):
    # Tengjast gagnagrunninum
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    # Lesa CSV gögnin inn í Pandas gagnagrunn
    df = pd.read_csv(csv_file)

    # Setja gögnin í töfluna timataka í gagnagrunninum
    for index, row in df.iterrows():
        # Finna hlaupið í hlaup töflunni eða setja inn nýtt hlaup ef það er ekki til
        cursor.execute('''
            INSERT OR IGNORE INTO hlaup (nafn, upphaf)
            VALUES (?, ?)
        ''', (row['Category'], '2024-01-01 10:00:00'))  

        # Finna hlaupið sem var sett inn (ef það var nýtt)
        cursor.execute('''
            SELECT id FROM hlaup WHERE nafn = ?
        ''', (row['Category'],))
        hlaup_id = cursor.fetchone()[0]

        # Setja keppandann inn í timataka töfluna
        cursor.execute('''
            INSERT OR IGNORE INTO timataka (hlaup_id, nafn, timi, kyn)
            VALUES (?, ?, ?, ?)
        ''', (hlaup_id, row['Name'], row['Time'], 'Ótilgreint'))  

    # Vista breytingar og loka gagnagrunninum
    conn.commit()
    conn.close()

```

2024-10-02 16:35 UTC, Jon-slow97 commented on timataka.py
> +
# Setja gögnin í SQLite gagnagrunninn
    insert_into_database(args.output, 'timataka_net.db')  # Gagnagrunnsnafnið er 'timataka_net.db'

2024-10-03 23:06 UTC, Thordisalda approved these changes
Looking good, readme skýrt um hvernig á að setja upp og kóðinn skilar útkomunni sem ég bjost við.

2024-10-03 23:18 UTC, Jon-slow97 approved these changes

2024-10-03 23:21 UTC, Jon-slow97 approved these changes
Verðum að skila þessu

2024-10-08 16:46 UTC, tungufoss commented
> Verðum að skila þessu

Á þetta að vera útistandandi PR? Þarf að merge'a þessu? Ég get gert það núna ef þið viljið.

2024-10-24 11:19 UTC, merged